### ISSUE TITLE
Update fields for episode_prep.yaml

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/Topics#46]
Update the yaml file at `.github/episode_prep.yaml` with the following Changes:

### Change the `title` to: `<EPISODE_TITLE>`
```title: "[Publish] Python Community <EPISODE NUMBER>" # Change to <EPISODE TITLE FROM YOUTUBE>```

### Change the `<shownotes id>` to `<podcast>`
```
 - type: input
    id: shownotes_id #Change this to Shownotes
    attributes:
      label: Shownotes ID
```
### Change the `<YouTube ID>` to `<YouTube>`
```
 - type: input
    id: youtube_id # Change to Youtube
    attributes:
```
